platform :ios, '10.0'

target 'Thot' do

    use_frameworks!
    
        pod 'Alamofire', '~> 4.7'

  target 'ThotTests' do
    inherit! :search_paths

  end

  target 'ThotUITests' do
    inherit! :search_paths

  end

end
